### ISSUE TITLE
품절 메시지 Convention 변경 요청

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#1]
![image](https://user-images.githubusercontent.com/26738367/66702074-7d73b100-ed3e-11e9-92ca-ba1121985f74.png)

is_sold_out 보다는 isSoldOut으로 표기 해 주시면 사용하기도 편하고 보기에 더 좋을 것 같습니다.

**Comment by kbs4674** [comment]
내일 바꿔놓을게용 :D

**Comment by kbs4674** [comment]
참, 그런데 저거 명칭 바꾸면 DB Drop하게 된다는 점 참고해주세용

**Comment by samslow** [comment]
@kbs4674  네 알겠습니다. PR 하실땐 Fix #1 이런 식으로 부탁드려요

**Comment by kbs4674** [comment]
Fix #1 명칭 변경완료
