### ISSUE TITLE
딜바다 : 점수계산을 다시해야할 것 같습니다.

### ISSUE THREAD

**Issue by kbs4674** [samslow/popStarMomi-BE-V2#12]
딜바다 사이트가 다른 사이트에비해 댓글이 너무 많이 달리다보니 (평균적으로 봤을 때 적어도 30~40개, 많으면 400개 이상) 딜바다 사이트는 점수계산을 다시해야 할 것 같습니다.

**Comment by samslow** [comment]
현재 Master에 있는 코드가 최신인가요 ? 
딜바다 데이터가 잘 오지 않는 것 같습니다. 확인 부탁드립니다.

**Comment by kbs4674** [comment]
넵, 최신자료 맞습니다.
더불어 자료도 크롤링이 잘 되는게 확인됩니다.

https://popstar-momi.herokuapp.com/hit_products/deal_ba_da

**Comment by samslow** [comment]
상대적으로 딜바다의 게시물이 적은 것 같습니다. AppCenter에서 최신 앱 받으시어 확인 부탁드립니다.

**Comment by kbs4674** [comment]
현재 크롤링은 한번 크롤링 당 2 목록까지만 크롤링이 이루어 지는 방식입니.
크롤링 대상의 홈페이지에서는 한 목록 당 루리웹에서는 28개, 클리앙 30개, 딜바다 15개, 뿜뿌 15개의 게시글이 보여지는 상태입니다.

일단 목록 당 게시글 상태만 봐서도 딜바다가 많이 뒤쳐집니다. 그런데 뿜뿌는 하루 게시글이 1목차를 넘을정도로 활발히 올라오는 상태라서 딜바다가 상대적으로 좀 게시글이 적게보일 수도 있습니다.
원하면 일부 홈페이지에 대해선 크롤링 목차를 넓힐 수 있습니다.

**Comment by samslow** [comment]
그럼 현안으로 가도 되겠네요. 설명 감사합니다.
