### ISSUE TITLE
camelCase로 변경 요청

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#14]
<img width="954" alt="스크린샷 2019-10-26 17 27 46" src="https://user-images.githubusercontent.com/26738367/67616613-034f2c00-f816-11e9-8b2e-7f92a582ac62.png">

![image](https://user-images.githubusercontent.com/26738367/67616625-237eeb00-f816-11e9-96ad-8c4b4b783844.png)

`IsSoldOut` →  `isSoldOut`

**Comment by kbs4674** [comment]
확인했습니다.
