### ISSUE TITLE
page 1 의 결과와 page 2 의 결과가 서로 중복되는 데이터가 있습니다.

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#15]
page 1 의 결과와 page 2 의 결과가 서로 중복되는 데이터가 있습니다.

각 페이지의 데이터가 겹치는 부분을 해결 부탁드립니다.

**Comment by kbs4674** [comment]
해결했습니다.
원인은 PostgreSQL DB 쿼리가 이상하게 돌아가서 그런 것 같습니다.
* 해결 : uniq 메소드를 넣어서 중복 값은 배제 처리
