### ISSUE TITLE
새롭게 추가해야 할 크롤링 사이트 요청

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#2]
현재 운용중인 사이트는 `뽐뿌` 와 `클리앙` 입니다.

추가적으로 핫딜을 긁어올 사이트 리스트 첨부합니다.

* [루리웹](https://bbs.ruliweb.com/market/board/1020)
* [딜바다](http://www.dealbada.com/bbs/board.php?bo_table=deal_domestic)

**Comment by kbs4674** [comment]
이건 좀 시간이 걸릴 것 같습니다 흙흙..
