### ISSUE TITLE
Json response date 에 시,분 까지 표현 요청

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#3]
데이터의 최신 여부를 알기위해 시 분까지 반영 해 주시길 바랍니다.

**Comment by kbs4674** [comment]
원본 게시글에서 시-분이 노출되면 할 순 있겠는데, 없으면 구현이 어려울 수도 있는 점 참고해주세요..!

**Comment by samslow** [comment]
아 그럼 이 이슈는 닫도록 하겠습니다. 다른 방법을 찾을때까진 보류입니다.
