### ISSUE TITLE
Security Alert 해결 요청

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#4]
![image](https://user-images.githubusercontent.com/26738367/66712527-f9223c00-edd8-11e9-927c-df8c4defacf2.png)

GitHub Repository에 Git Guardian 에서 Catch된 보안 알림을 해결 해 주세요.

simple_form Gem 의 문제 인 것 같습니다.

**Comment by kbs4674** [comment]
simple_form Gem 같은 경우 `rails_db`에서 simple_form Gem을 의존(dependency)하고 있어서 현재는 삭제가 어려울 것 같습니다. 해당 문제는 잠시 보존하겠습니다.
