### ISSUE TITLE
Infinite Scroll 구현을 위한 pagable한 url 요청

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#5]
현재 url에서 page를 파라미터로 보내면 현재 DB에 있는 데이터에서 각 페이지에 맞는 데이터를 보내주세요.

* page는 전체 포스트가 담겨있는 배열의 각 페이지를 의미합니다.

예를들어

(OUR URL)/page=1이면 

1번째 페이지를 보여주세요. 

**단 여기서 각 페이지는 20개씩 보내주시면 됩니다.**

**Comment by kbs4674** [comment]
이건 좀 구현에 있어 설계가 문제있는게, 게시글은 계속 쌓이면서 초반에 수집했던 글은 계속 목록이 밀려나는 문제가 있어서 정확한 page parameter까지 전해주긴 어려울 것 같아요..

**Comment by samslow** [comment]
@kbs4674 최신 것부터 20개만 보내주시면 됩니다. 어떤 부분이 어려운가요

**Comment by kbs4674** [comment]
크롤링 대상의 페이지를 순회할 때 마다 page 카운팅이 올라가게 구현해두 될까여?

* 예시
클리앙 1목록 페이지 크롤링 후 output => page_stack: 1
클리앙 2목록 페이지 크롤링 후 output => page_stack: 2
뿜뿌 1목록 페이지 크롤링 후 output => page_stack: 3

**Comment by samslow** [comment]
@kbs4674 잘 이해가 가지 않습니다. Client에서는 page로 요청 드릴거기때문에 사이트를 구분 하지 않으셔도 됩니다.

**Comment by kbs4674** [comment]
넵 알겠습니다

**Comment by kbs4674** [comment]
요구사항대로 했습니다 :)

**Comment by samslow** [comment]
![image](https://user-images.githubusercontent.com/26738367/66716675-664ec500-ee0b-11e9-8471-71447ca28267.png)
해결 되었다고 했는데 페이지 넘기니까 에러가 납니다 확인 부탁드립니다.

그리고 이 문제는 PR로 넘겨주세요

**Comment by kbs4674** [comment]
아 저런식으로 해야하는구나..
다시 코드 조절할게요

**Comment by kbs4674** [comment]
혹시 `https://60b3954b-a7b2-4fba-b2e8-9d53e2f9dbdb.mock.pstmn.io/?page=1` 이런 형식은 안될까요? 유동적인 query에 대해선 ?로 구분을 해야 하더라고요.

**Comment by kbs4674** [comment]
그런데 또 생각해보니 page가 올라가는 구현에 있어 유의해야되는게 page는 끊임없이 올라갑니다.
저야 page의 최솟값, 최댓값은 Console을 이용해서 확인 가능하나, samslow 님에게 있어 page의 최댓값, 최솟값은 어떻게 확인할지에 대한 고민을 해야할 수도 있습니다.

**Comment by kbs4674** [comment]
일단 대략적으로 구현은 했는데, 한번 원하는 의도대로 됐는지 확인해주세요.
* URL Parameter 사용법
`https://popstar-momi.herokuapp.com/hit_products/condition?page=1`

**Comment by samslow** [comment]
@kbs4674 
1. 물음표 추가는 제가 놓친 부분이었네요. 추가해주시면 좋을 것 같습니다.

2. DB에서 비워지는 주기가 얼마인가요? 
현재는 200개 가량인데 20개씩 한 페이지이니 10개정도인거 같은데 맞나요?

**Comment by kbs4674** [comment]
- 데이터는 크롤링 한지 2일이 지나면 삭제됩니다.
- `https://popstar-momi.herokuapp.com/hit_products/condition?page=1` 로 접속 시, 한 페이지당 10개씩 보여집니다.

**Comment by samslow** [comment]
20개로 조정 부탁드립니다. 갤럭시 노트같은 경우는 한 화면에 10개는 좀 모자를 거에요

**Comment by kbs4674** [comment]
다시 재수정 해서 구현했습니다.
이제 page parameter을 몇으로 주느냐 따라 테이블에서 page*10~page*10+20 단위로 글을 가져옵니다.

예시 : page = 4인 경우
40번째 ~ 60번째의 글을 가져옴.

**Comment by kbs4674** [comment]
개인적으로 하나 더 이슈를 하고싶은데요,

page = 2인 경우 20번 째 ~ `40번 째`의 글을 수집하고
page = 3인 경우 `40번 째` ~ 60번 째의 글을 수집합니다.

그런데 위 방식대로 하면 글이 중복으로 겹치는 부분이 존재하는데, 저렇게 중복이 보여져도 상관없을까요, 아니면 중복이 안나오게 조율을 해야할까요?

**Comment by samslow** [comment]
@kbs4674 
네 중복되는 부분은 빠져야 합니다. 
ID를 에시로 들자면 0~19까지 20개 
20~39까지 20개 이런식으로  나뉘어져야 중복이 안 생기겠죠 ?

**Comment by kbs4674** [comment]
원래 `pages`라고 할려했는데.. 이상하게도 output으로 보면 안보이더라구요..

**Comment by samslow** [comment]
@kbs4674 그럼 pageNumber는 어떤가요 ?

**Comment by kbs4674** [comment]
좋습니다.
