### ISSUE TITLE
일부 값들이 null로 오는 문제

### ISSUE THREAD

**Issue by samslow** [samslow/popStarMomi-BE-V2#7]
![image](https://user-images.githubusercontent.com/26738367/66716721-1a505000-ee0c-11e9-8969-64204d6ec183.png)

이 문제는 메신저 상으로 나온 이슈지만 이슈에 따로 남겨놓습니다.

서버 스크래핑쪽 문제이고 Dynamic IP 같은 기능이 필요 해 보입니다.

**Comment by kbs4674** [comment]
Heroku 환경 상 다이나믹 IP는 아마 수동으로 해야할겁니다..ㅠ

**Comment by samslow** [comment]
네 Dynamic IP는 예시였고 필요한 방법으로 구현 부탁드립니다.

**Comment by samslow** [comment]
@kbs4674 혹시
